### ISSUE TITLE
I want to execute 'tum_rgbd.py'

### ISSUE THREAD

**Issue by choibigo** [qcr/quadricslam#17]
- I downloaded tum dataset via 'get_tum_rgbd_datasets'
- when i executed 'tum_rgbd.py' this error occurred

```
Traceback (most recent call last):
  File "/home/cbigo/workspace/quadricslam/src/quadricslam_examples/tum_rgbd.py", line 58, in <module>
    run()
  File "/home/cbigo/workspace/quadricslam/src/quadricslam_examples/tum_rgbd.py", line 48, in run
    q = QuadricSlam(
  File "/home/cbigo/anaconda3/envs/gtsam/lib/python3.9/site-packages/quadricslam/quadricslam.py", line 46, in __init__
    raise NotImplementedError('No default data associator yet exists, '
NotImplementedError: No default data associator yet exists, so you must provide one.
```

- So i browsed your issues and then i could find this page(https://github.com/qcr/quadricslam/issues/3)
- I want to execute this code, Could you give me some tips for solving this problem?

Thank you @btalb

**Comment by park-dea** [comment]
I have same error. 
How can i solve it?

**Comment by notu97** [comment]
Just  use the IOU based Associator: 
from quadricslam.data_associator.quadric_iou_associator import QuadricIouAssociator
