### ISSUE TITLE
[tum_rgbd.py] missing 2 required positional arguments: 'labels' and 'done'

### ISSUE THREAD

**Issue by notu97** [qcr/quadricslam#18]
I get this issue while trying to run the tum_rgbd.py file. I have defined the data associator already.

'Traceback (most recent call last):
  File "/home/shiladitya/anaconda3/envs/gslam/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/shiladitya/anaconda3/envs/gslam/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/shiladitya/anaconda3/envs/gslam/lib/python3.10/site-packages/quadricslam_examples/tum_rgbd.py", line 56, in <module>
    run()
  File "/home/shiladitya/anaconda3/envs/gslam/lib/python3.10/site-packages/quadricslam_examples/tum_rgbd.py", line 52, in run
    q.spin()
  File "/home/shiladitya/anaconda3/envs/gslam/lib/python3.10/site-packages/quadricslam/quadricslam.py", line 135, in spin
    self.step()
  File "/home/shiladitya/anaconda3/envs/gslam/lib/python3.10/site-packages/quadricslam/quadricslam.py", line 213, in step
    self.on_new_estimate(self.state)
TypeError: run.<locals>.<lambda>() missing 2 required positional arguments: 'labels' and 'done'
'
Here is a screen shot of my code:
![image](https://github.com/user-attachments/assets/01f98511-79f5-4695-80c3-c5f112436609)

**Comment by xinzhichao** [comment]
I've encountered the same problem. May I ask if you've solved it?
